name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master  # или другая ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.PI_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Pull latest changes on Raspberry Pi
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -o IdentitiesOnly=yes \
            -o UserKnownHostsFile=/dev/null \
            -o StrictHostKeyChecking=no \
            ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} \
            "cd /home/maksekak/myapp/zapisBot && git pull origin main"
