name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master  # или другая ветка, например, master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/actionKey
          chmod 600 ~/.ssh/actionKey
          ssh-keyscan -H ${{ secrets.PI_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Pull latest changes on Raspberry Pi
        run: |
          ssh -i ~/.ssh/actionKey -o IdentitiesOnly=yes ${{ secrets.PI_NAME }}@${{ secrets.PI_HOST }} \
          "cd myapp/zapisBot && git pull origin main"
